const appsData = [
    {
        id: 1,
        name: "PUBG Mobile Hack (ESP/Aim)",
        version: "3.1.0",
        features: "كشف مكان العدو + كويك سكوب",
        size: "780 MB",
        category: "games",
        downloads: "2.4M",
        rating: "4.8",
        isHot: true,
        icon: "images/pubg.png",
        downloadLink: "https://www.mediafire.com/file/xxxxxx/pubg_mod.apk",
        description: "نسخة مهكرة خاصة بلعبة ببجي موبايل تحتوي على تفعيل ميزات المساعد الذكي وكشف الأماكن بدون حظر حساب أساسي عند اللعب بحذر."
    },
    {
        id: 2,
        name: "Subway Surfers Mod",
        version: "3.20.0",
        features: "أموال ومفاتيح غير محدودة",
        size: "45 MB",
        category: "mods",
        downloads: "5.1M",
        rating: "4.9",
        isHot: true,
        icon: "images/subway.png",
        downloadLink: "https://www.mediafire.com/file/xxxxxx/subway.apk",
        description: "النسخة الشهيرة بأموال لا تنتهي ومفاتيح مجانية لفتح جميع الشخصيات ولوح التزلج فوراً."
    },
    {
        id: 3,
        name: "Telegram Premium Unlocked",
        version: "10.6.0",
        features: "فتح المميزات المدفوعة والتحميل السريع",
        size: "95 MB",
        category: "apps",
        downloads: "1.8M",
        rating: "4.7",
        isHot: false,
        icon: "images/telegram.png",
        downloadLink: "https://www.mediafire.com/file/xxxxxx/telegram.apk",
        description: "تطبيق تيليجرام معدل يتيح لك الاستمتاع بكافة مزايا الحساب المدفوع مجاناً بالكامل."
    },
    {
        id: 4,
        name: "Free Fire Max Mod",
        version: "2.108.1",
        features: "أيم بوت + هيدشوت تلقائي",
        size: "520 MB",
        category: "games",
        downloads: "3.9M",
        rating: "4.6",
        isHot: true,
        icon: "images/freefire.png",
        downloadLink: "https://www.mediafire.com/file/xxxxxx/freefire.apk",
        description: "لعبة فري فاير ماكس بنسخة مطورة تمنحك دقة تصويب خارقة وتجاوز العقبات بسهولة فائقة."
    },
    {
        id: 5,
        name: "Spotify Premium Mod",
        version: "8.9.2",
        features: "بدون إعلانات + تخطي غير محدود",
        size: "75 MB",
        category: "apps",
        downloads: "4.2M",
        rating: "4.9",
        isHot: true,
        icon: "images/spotify.png",
        downloadLink: "https://www.mediafire.com/file/xxxxxx/spotify.apk",
        description: "استمتع بالاستماع للموسيقى المفضلة لديك بدون أي إعلانات مزعجة مع إمكانية التحميل للاستماع بدون انترنت."
    },
    {
        id: 6,
        name: "Shadow Fight 2 Special Edition",
        version: "2.28.0",
        features: "طاقة لا نهائية + أموال",
        size: "140 MB",
        category: "games",
        downloads: "950K",
        rating: "4.8",
        isHot: false,
        icon: "images/shadowfight.png",
        downloadLink: "https://www.mediafire.com/file/xxxxxx/shadowfight.apk",
        description: "لعبة القتال الأسطورية مع تعديلات تمنحك طاقة غير محدودة وقوة قصوى لتدمير الزعماء."
    }
];
